# 閉じタグを挿入する
[[plugins]]
repo = 'alvan/vim-closetag'

# emmetをサポートする
[[plugins]]
repo = 'mattn/emmet-vim'


[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'preservim/nerdtree'

# コメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

# シンタックスハイライト
[[plugins]]
repo = 'sheerun/vim-polyglot'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
marged = 0
rev = 'release'

[[plugins]]
repo = 'vim-airline/vim-airline'

