# 閉じタグを挿入する
[[plugins]]
repo = 'alvan/vim-closetag'

# emmetをサポートする
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'preservim/nerdtree'

# コメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

# シンタックスハイライト
[[plugins]]
repo = 'sheerun/vim-polyglot'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
marged = 0
rev = 'release'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

# 置換を強化
[[plugins]]
repo = 'markonm/traces.vim'

# アイコンを表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install
# '''

[[plugins]]
repo = 'junegunn/fzf.vim'
