### ファイルの編集 #########################################
# 閉じタグを挿入する
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.tpl,*.jsx,*.vue'
'''

# emmetをサポートする
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_do_mapping = 0
nmap <space>s <plug>(easymotion-overwin-f2)
nmap <space>w <plug>(easymotion-overwin-w)
'''

# コメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

# 置換を強化
[[plugins]]
repo = 'markonm/traces.vim'

# シンタックスハイライト
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disable = ['csv']
'''

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
marged = 0
rev = 'release'
hook_add = '''
nmap <space>ho :<C-u>call CocAction('doHover')<cr>
nmap <space>df <Plug>(coc-definition)
nmap <space>rf <Plug>(coc-references)
nmap <space>rn <Plug>(coc-rename)
# スクリプトの実行
[[plugins]]
repo = 'thinca/vim-quickrun'

# [[plugins]]
# repo = 'LeafCage/yankround.vim'
# hook_add = '''
# nmap p <Plug>(yankround-p)
# xmap p <Plug>(yankround-p)
# nmap P <Plug>(yankround-P)
# nmap gp <Plug>(yankround-gp)
# xmap gp <Plug>(yankround-gp)
# nmap gP <Plug>(yankround-gP)
# nmap <C-p> <Plug>(yankround-prev)
# nmap <C-n> <Plug>(yankround-next)
# '''


### ファイルを開く #########################################
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <space>o :NERDTreeToggle<CR>
nnoremap <space>n :NERDTreeFocus<CR>
let NERDTreeShowHidden=1
'''

# editor config
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# fzf
# [[plugins]]
# repo = 'junegunn/fzf'
# build = '''
# ./install
# '''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <space>f :Files<CR>
set rtp+=~/.fzf
'''


### サポート ###############################################
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
let g:cheatsheet#cheat_file = '~/dotfiles-193/vim/cheatsheet'
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
let g:dein#install_process_timeout=119
'''


### 見た目 #################################################
[[plugins]]
repo = 'vim-airline/vim-airline'

# アイコンを表示
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

