# 閉じタグを挿入する
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.tpl,*.jsx,*.vue'
'''

# emmetをサポートする
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_do_mapping = 0
nmap <space>s <plug>(easymotion-overwin-f2)
nmap <space>w <plug>(easymotion-overwin-w)
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <space>o :NERDTreeToggle<CR>
nnoremap <space>n :NERDTreeFocus<CR>
let NERDTreeShowHidden=1
'''

# コメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

# シンタックスハイライト
[[plugins]]
repo = 'sheerun/vim-polyglot'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
marged = 0
rev = 'release'
hook_add = '''
nmap <space>df <Plug>(coc-definition)
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
let g:dein#install_process_timeout=119
'''

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

# 置換を強化
[[plugins]]
repo = 'markonm/traces.vim'
hook_add = '''
nmap p <Plug>(yankround-p)
xmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)
nmap gp <Plug>(yankround-gp)
xmap gp <Plug>(yankround-gp)
nmap gP <Plug>(yankround-gP)
nmap <C-p> <Plug>(yankround-prev)
nmap <C-n> <Plug>(yankround-next)
'''

# アイコンを表示
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install
'''
hook_add = '''
nnoremap <space>f :Files<CR>
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
